sudo: false
rvm:
- 1.9.3
- 2.0
- 2.1
- 2.2
- 2.3.0
- jruby-1.7.23
- jruby-9.0.4.0
otp_release:
- 18.2.1
matrix:
  allow_failures:
  - rvm: jruby-1.7.23
env:
  - PATH=$PATH:$HOME/gradle/bin:$HOME/rebar:$HOME/go/bin:$HOME/kerl:$HOME/erlang:$HOME/elixir/bin GOPATH=$HOME/go
notifications:
  email:
  - licensefinder@pivotallabs.com
  webhooks:
    urls:
    - http://pulse.pivotallabs.com/projects/657d35b7-b896-4bf3-8837-9d558e2ab651/status
    on_start: true
  slack:
    secure: VIrS65Ssun4Jpu6Y5DpZFAjNmsxVBHxqa2VbrwghibhdhUksxQtit4a7ncGrgEoOMYMZfETjB0SD15au+Dx3TbVS+yuLk7lP5cI2Yf37Q87+hGRRY1FpuPtF45/r1CTHqv8GyVvz2RMwyDYYoLeSl62CUpJatm/+z9x6q2EImJo=
before_install:
- gem update bundler
- ".travis/install_gradle.sh"
- ".travis/install_rebar.sh"
- ".travis/install_bower.sh"
- ".travis/install_godep.sh"
- ".travis/install_mix.sh"
before_script:
- kerl update releases
- kerl list installations
script:
- . /erlang/activate
- erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().' -noshell
- rake install
- rake spec
- rake features
